#Vars
Would you like to use Basic mode: "y"
Please provide ansible-vault key for password encryption: "abIniti0"
ab_aiuser_name:  "abinitio"
ab_aiuser_group:  "abinitio"
ab_key_host_source: 'server'
ab_key_client_host_urls: 'abks://SIKEY.abinitio.com:50116'
ab_key_users_source: 'server'
#ab_key_client_users_bundle_name: 'RYPE01'
ab_key_client_users_urls: 'abks://SIKEY.abinitio.com:50115'
ab_tmp_dir: '/data/tmp'
act_base_port_prefix: '290'
act_name: 'act360'
act_portal_scaled_binary_type_decimal_places: '2'
act_root: /data/act360
act_data_root: /data/act360
act_config_dir: /disk1/act360/config
act_runtime_messagebus_commit_topic_width: '1'
act_runtime_messagebus_topic_width: '3'
act_runtime_messagebus_log_entry_topic_width: '3'
act_runtime_messagebus_log_accum_topic_width: '3'
act_runtime_messagebus_service_reject_topic_width: '3'
installer_cloud : 'True'

